"""Add percent_gain column to Stock

Revision ID: 29fab4506a2c
Revises: 064f8449ff8a
Create Date: 2023-08-26 16:56:26.100210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29fab4506a2c'
down_revision = '064f8449ff8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percent_gain', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('percent_gain')

    # ### end Alembic commands ###
